# config/routes.yaml
blog:
    path: /blog
    # the controller value has the format 'controller_class::method_name'
    controller: Mybasicmodule\Controller\CommentController::indexAction

blog_list:
    path: /blog/list
    # the controller value has the format 'controller_class::method_name'
    controller: Mybasicmodule\Controller\CommentController::listAction
    # if the action is implemented as the __invoke() method of the
    # controller class, you can skip the '::method_name' part:
    # controller: App\Controller\BlogController